stages:
  get_data:
    cmd: python src/main/stage_01_get_data.py --config=configs/config.yaml
    deps:
      - src/main/stage_01_get_data.py
      - src/utils/utils.py
      - configs/config.yaml
      - configs/logging.py
    outs:
      - data/data.xml

  prepare_data:
    cmd: python src/main/stage_02_prepare_data.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/main/stage_02_prepare_data.py
      - data/data.xml
      - src/utils/utils.py
      - src/utils/data_management.py
      - configs/config.yaml
      - params.yaml
      - configs/logging.py
    params:
      - prepare_data.seed
      - prepare_data.split  
    outs:
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv

  featurize:
    cmd: python src/main/stage_03_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/main/stage_03_featurization.py
      - src/utils/utils.py
      - src/utils/featurize.py
      - artifacts/prepared_data/train.tsv
      - artifacts/prepared_data/test.tsv
      - configs/config.yaml
      - configs/logging.py
    params:
      - featurize.max_features
      - featurize.ngrams  
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl