artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared_data
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

source_download_dir:
  data_dir: data
  data_file: data.xml

encoding: utf8

plots:
  PRC: prc.json
  ROC: roc.json

metrics:
  SCORES: scores.json