# add ci-cd steps here
name: NLP-STACKOVERFLOW-CLASSIFICATION

on: [push]

jobs:
  run: 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: cml-run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_DATA_URL: ${{ secrets.SOURCE_DATA_URL }}
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro         
          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat scores.json >> report.md
          dvc metrics show >> report.md
          cml-send-comment report.md

